### ISSUE TITLE
Вопросы к Домашнее задание 1

### ISSUE THREAD

**Issue by saloznavets** [danbravo/goIT#1]
Вполне годная иерархия классов. Только есть следующее замечание:

Вы сделали различных наследников, но смысл в наследовании не показали. Я имею в виду, что классы у вас пустые и никак не специфицируют классы родители и классы потомки.

И еще одно, я ни в коем случае не назову это ошибкой, но, думаю, можем обсудить что же должен в себе содержать музыкальный магазин.

**Comment by abbystasja** [comment]
1. Создать классы Текстовый файл, Аудио файл, Файл изображения, используя класс Файл. Создать класс Директория,  содержащий файлы разных форматов.

Наследование реализовано правильно. Немного неправильно понято понятие абстракции.
Смотри - Если каждый файл (текстовый, графический и т.д.) являються файлами, то не обязательно включать каждый тип файла в директорию, достаточно только абсракцию.

2. По поводу цветов то же самое замечание. Тут другое обьяснение. Если у тебя не существует маргариток - то ты никогда не сможешь собрать букет даже если есть все остальный цветы.

По этому в букет должен входить только главна абстракция - цветок.

Почему розовый кус наследуеться от розы?? он наверное состоит из роз а не расширяет функционнальность розы.

3. Та же ошибка.
Если не разберешься попробую завтра по другому обьяснить

**Comment by danbravo** [comment]
исправил

**Comment by saloznavets** [comment]
Хорошо, все правильно. Но почему классы пустые?
Добавь поля класса и в родительский класс и в потомок. Так, чтоб потомки как бы расширяли родителя. Поля не должны дублироваться.

**Comment by danbravo** [comment]
исправил (2)
